baseURL = 'https://damiangalarza.com'
languageCode = 'en-us'
title = 'Technical Partner for Startups | Damian Galarza, Fractional CTO'
#paginate = 3
# theme = 'maverick' # Removed theme to use custom layouts

[permalinks]
  pages = "/:slug"

[params]
  logo = '/assets/favicon.ico'
  description = "I help early-stage startup founders build better software, faster — from MVPs and architecture reviews to AI integration and fractional CTO support"
  author = 'Damian Galarza'
  
  [params.social]
    linkedin = "https://www.linkedin.com/in/dgalarza/"
    github = "https://github.com/dgalarza"
    twitter = "https://twitter.com/dgalarza"

  [params.comments]
    enabled = false
    githubRepo = 'canhtran/maverick'
    theme = 'github-light'


[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Post"
    url = "/posts/"
    weight = -200

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'catppuccin-mocha'
    tabWidth = 2

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

ignoreErrors = ["error-remote-getjson"]
